### ISSUE TITLE
[Bug] Check desktop yaml file for missing entities

### ISSUE THREAD

**Issue by poudenes** [dummylabs/thewatchman#106]
I love this tool so much!!!

Would be nice to have also a service check that will screen the desktop yaml file (Lovelace file).
Sometimes I change something and forget the desktop yaml file. So when The Watchman will check this and say where in the file (line number) is the error you can easy open the editor and then raw configuration and goto the line number.

Greets,
Peter

**Comment by ildar170975** [comment]
> will screen the desktop yaml file (Lovelace file).

Doesn't the Watchman "screen" it already?

**Comment by poudenes** [comment]
What I know its check all the integration and automation files. I never saw an issue from the desktop file. When check the desktop I see some missing entities and then have to update them. Or I see that something is not working anymore and then there was still a old entity.

**Comment by ildar170975** [comment]
Sorry, I am not getting. Are you describing:
-- what you can do already,
-- or are you describing what you want to do - but cannot currently?

**Comment by Hiekkaharju** [comment]
> > will screen the desktop yaml file (Lovelace file).
> 
> Doesn't the Watchman "screen" it already?

Yes it can. It's controlled by a by-default-off checkbox setting in the configuration of Watchman

**Comment by poudenes** [comment]
> > > will screen the desktop yaml file (Lovelace file).
> > 
> > 
> > Doesn't the Watchman "screen" it already?
> 
> Yes it can. It's controlled by a by-default-off checkbox setting in the configuration of Watchman

Do you mean that I have turn on this box: Parse dashboards UI (ex-Lovelace) configuration?

**Comment by poudenes** [comment]
If I do that then I have Missing Entities: 323.
That's incorrect. Then my whole dashboard won't work haha.

The missing entities are in : lovelace-latest and lovelace

**Comment by ildar170975** [comment]
> I have Missing Entities: 323.

Then register a bug issue with a detailed description.

**Comment by Hiekkaharju** [comment]
> > I have Missing Entities: 323.
> 
> Then register a bug issue with a detailed description.

No. First read the current open issues. Then check where the missing entries come from. Only if you find some false positives  that do not match to already existing open issues, report a new one.

**Comment by poudenes** [comment]
There is something going on. 

Here all missing entities 
[missing.txt](https://github.com/dummylabs/thewatchman/files/12776573/missing.txt)

and below my running dashboard:
[desktop.txt](https://github.com/dummylabs/thewatchman/files/12776574/desktop.txt)

It doesn't make sense.

**Comment by ildar170975** [comment]
At least first 3 entities reported as "missing" in "missing.txt" are missing in "desktop.txt".
Means - these entities are not mentioned explicitly by their names in this file - i.e. in this dashboard.
But Watchman is supposed to mark as "missing" an entity which is mentioned in a dashboard - but does not exist.
Are you sure that this "desktop.txt" file is exactly the dashboard which was monitored?
Are you sure that this "missing.txt" file is the latest analysis?


P.S. Suggest to rename the issue. It is not a "FR", it is about some bug (or what you suspect to be a bug).

**Comment by Hiekkaharju** [comment]
Big majority of all items in "missing" seem to come from file .storage/lovelace-latest  
I've never seen a such file in my system.  I'd suggest first figuring out what that file is.
In the end there are some items from .storage/lovelace , those might be real ones

**Comment by poudenes** [comment]
To be clear: desktop.txt file is the running dashboard(desktop). no errors, no missing entities. All ok. That's why its so weird that I get almost 323 missing entities when I enable "Parse dashboards UI (ex-Lovelace) configuration" in Watchman configuration.

I grab the desktop information by doing:
1) Right upper corder, edit dashboard
2) 3 dots, raw configuration editor

**Comment by Hiekkaharju** [comment]
Looking at the date of lovelace-latest I'd QUESS that it is some old backup. I did not have HA back in 2020. Might be that watchman is simplifying things by checking everything that begins with lovelace... I'd do a backup, rename that file to something else than lovelace... and restart.

**Comment by poudenes** [comment]
I think the problem has been solved. I removed the 'lovelace-latest' restart HA and now missing entities are 7.

**Comment by aubreyz** [comment]
I know this is a slightly old and closed issue - but I am confused. Watchman continues to show hundreds of missing dashboard entities after they are corrected and even after a restart. Obviously it is looking at various other files, but I have no idea how to correct this

**Comment by ildar170975** [comment]
> Watchman continues to show hundreds of missing dashboard entities after they are corrected and even after a restart

Was the Watchman asked to update it's sensors?

**Comment by aubreyz** [comment]
> > Watchman continues to show hundreds of missing dashboard entities after they are corrected and even after a restart
> 
> Was the Watchman asked to update it's sensors?

Yes several times via service Watchman: report. All of the non dashboard errors were corrected perfectly. 

I'm guessing there must be some lovelace backup files that are maintained by the dashboard system that are being examined by Watchman? I tried as an additional test to switch off "Parse dashboards" rerun the service (error count then falls to zero) and then switch "Parse Dashboards" back on again and run service again - and the errors are restored. So clearly it is looking at something that is not in the live dashboards...

Happy to help figure this out but not sure where to look

**Comment by aubreyz** [comment]
> > > Watchman continues to show hundreds of missing dashboard entities after they are corrected and even after a restart
> I'm guessing there must be some lovelace backup files that are maintained by the dashboard system that are being examined by Watchman? I tried as an additional test to switch off "Parse dashboards" rerun the service (error count then falls to zero) and then switch "Parse Dashboards" back on again and run service again - and the errors are restored. So clearly it is looking at something that is not in the live dashboards...
> 
> Happy to help figure this out but not sure where to look

Actually put this on hold for the moment - I am probably having a dumb moment.

**Comment by aubreyz** [comment]
Apologies - this was me. There was a slightly obscure massive sub-tab in a panel that I missed despite having Watchman point it out clearly. This is a great package!
