### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Max6993109** [dummylabs/thewatchman#107]
Hello, 

I recently restored my HA instance and as a result, my Watchman integration was not loading.  I tried to reinstall the integration and I would get this error: 

Config flow could not be loaded: {"message":"Invalid handler specified"}

I tried deleting the integration and couldn't until I went to .storage/core.config_entries.  I was able to then delete it from HACS and redownload it.  However, when I try to add the integration again, it continues to give me the above error message.  Not sure what else to do.

**Comment by dummylabs** [comment]
Unfortunately I cannot reproduce this, may be some extra registry cleanup required after restoration process which went not very smooth. Watchman load and init steps should work according to the developer guidelines.
