### ISSUE TITLE
Entities under mqtt: integration not detected

### ISSUE THREAD

**Issue by thermseekr** [dummylabs/thewatchman#110]
Just reporting, in case this is something to be adjusted: I have several sensors declared as `binary_sensor:` under the `mqtt:` integration that are showing as unknown in the report. See images below.

<img width="548" alt="Captura de Tela 2023-11-13 às 22 19 55" src="https://github.com/dummylabs/thewatchman/assets/48183960/7d648bba-e336-4a16-ac11-726bc84ec425">

<img width="374" alt="Captura de Tela 2023-11-13 às 22 21 01" src="https://github.com/dummylabs/thewatchman/assets/48183960/9e5a7bb3-4c7c-4344-85da-be5f43c29809">

<img width="442" alt="Captura de Tela 2023-11-13 às 22 23 47" src="https://github.com/dummylabs/thewatchman/assets/48183960/d23bd40a-ef79-4dd8-8ac9-12dda26135f2">

Thank you very much for providing this integration, it is super useful, helped me a lot.

**Comment by dummylabs** [comment]
From watchman perspective it means that these sensors were either unavailable or unknown at the moment report was generated.  Some platforms may take extra time after HA restart to initialize their sensors, those will be shown as missing in the report. If this is your case, try to adjust startup delay in the WM options.
