### ISSUE TITLE
Feature Request View full parsed configuration file

### ISSUE THREAD

**Issue by TBobsin** [dummylabs/thewatchman#111]
Hello,
if you work with many !include... options sometimes it is difficult to understand why the configuration is not working. Or just want to see all together for debugging purposes.
HA has no option to show the resulting YAML file with all !includes ...
Please add an option to save the linked configuration file example as  configuration_linked.txt

**Comment by ildar170975** [comment]
I guess this is much far from the initial goal of the Watchman plugin.

**Comment by dummylabs** [comment]
At the moment, Watchman lacks information about the structure and relationships among different parts of configuration files and their semantics. It simply parses all configuration files for entities/services definitions in specified folders in a random order.
