### ISSUE TITLE
Mistaken missing entity detection

### ISSUE THREAD

**Issue by zavrazhny** [dummylabs/thewatchman#113]
Watchman reports missing entity which is attribute indeed.

Config example:
![Screen Shot 2024-01-17 at 8 02 18 AM](https://github.com/dummylabs/thewatchman/assets/56259169/3409b060-b7cc-48c0-b6af-887c7ef85f06)

Report:
![Screen Shot 2024-01-17 at 7 59 53 AM](https://github.com/dummylabs/thewatchman/assets/56259169/29590a36-b263-4865-b0c0-6b622ef3a79e)

**Comment by zavrazhny** [comment]
Sorry, I forgot to attach entity properties:
![Screen Shot 2024-01-17 at 8 03 52 AM](https://github.com/dummylabs/thewatchman/assets/56259169/c3249353-d53e-4aac-9c94-a8599da12a4d)

**Comment by dummylabs** [comment]
I don't think there's an easy way to parse such references correctly, at least not while it's done via regex. It seems a bit odd that the integration authors added the humidifier. suffix to some attributes of a humidifier entity. Anyway, the only solution so far is to add these to the ignored items list.
