### ISSUE TITLE
images not found

### ISSUE THREAD

**Issue by 532910** [dummylabs/thewatchman#119]
![image](https://github.com/dummylabs/thewatchman/assets/14617699/9908afef-5da3-4e86-a083-d76844b636ca)

latest haos

**Comment by ildar170975** [comment]
What is this about? Care to add some explanations?

**Comment by 532910** [comment]
about 404 errors on images as shown on the screenshot above

**Comment by ildar170975** [comment]
I mean - where are you trying to see these data, in a browser? In HACS?

**Comment by 532910** [comment]
in hacs

**Comment by 532910** [comment]
image urls point to my ha, for example: https://myha.tld/images/service_example.png

**Comment by 532910** [comment]
installation changes nothing

**Comment by 532910** [comment]
I pressed "Update information" and reloaded page with shift several times, but it still doesn't work ):
