### ISSUE TITLE
false positives on jinja template variables

### ISSUE THREAD

**Issue by lanrat** [dummylabs/thewatchman#12]
My report generates some false positives for missing entities belonging to template variables inside automation and scripts.

See below for the example on `light.attributes` which is a variable in a script:

![image](https://user-images.githubusercontent.com/164192/155199935-bd10274c-dd15-4f7e-b6fb-3c0b56339beb.png)

Relevant lines from the script:

```yaml
variables:
  lights_auto: >
    {% set lights = namespace(color=[]) %} {% for light in states.light |
    selectattr('attributes.supported_color_modes') %}
      {% if ('rgb' in light.attributes.supported_color_modes) or ('hs' in light.attributes.supported_color_modes) %}
        {% set lights.color = lights.color + [ light ] %}
      {% endif %}
    {% endfor %} {{ lights.color | map(attribute="entity_id") | list }}
```

I suspect parsing the scripts correctly to identify the correct fields on each object would be out of scope. So would it be possible to detect dynamic variables and exclude them from watchtower?

**Comment by dummylabs** [comment]
So far it is not possible to detect such things by watchman as it works with configuration files and has no access to the jinja runtime context. To exclude such false positives from the report you can use `ignored_items` parameter in watchman options. It accepts both exact item names and wildcard patterns (there are examples in the documentation).

**Comment by lanrat** [comment]
I understand that I can use `ignored_items`, but I'd need to go find every variable name I use all over HASS and add it there right?

What I'm suggesting is to allow watchman to not scan variables at all since they will almost always be false positives.

**Comment by dummylabs** [comment]
Correct. I see two options (both require some extra effort):
1. Use ignored_items
2. Change your variable names so that they do not start from "light." or other Home Assistant domains. 

Under the hood watchman uses regular expressions to detect entities and sensors in configuration files, this is why `light.*` entries are detected as entities. If you have an idea of a regular expression for rubust detection of jinja variables - I'll be happy to adopt a PR.

**Comment by dummylabs** [comment]
If you suggest to ignore templates at all - this is not the case either, as many real entities will be ignored that way.

**Comment by lanrat** [comment]
Oh, It did not occur to me that I was using the same variable name in my template as a HASS domain.
I renamed the variables and now I no longer get false positives!
