### ISSUE TITLE
HomeAssistantType is a deprecated alias

### ISSUE THREAD

**Issue by tomlut** [dummylabs/thewatchman#127]
Testing HA core 2024.5.b0 produces this error:

HomeAssistantType was used from watchman, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'watchman' custom integration

**Comment by sven-debug** [comment]
Dears,

any idea when this will be released? 

BR
Sven

**Comment by popy2k14** [comment]
+1 for a release.
thx

**Comment by ondras12345** [comment]
This repo seems to be stale. However, there is a new fork that has fixed this and released a beta: https://github.com/andreasbrett/thewatchman

**Comment by popy2k14** [comment]
@ondras12345  thx for the hint
Tried the 0.6.2 beta0 and it fixed the issue for me.

thx a lot.
Also @andreasbrett :-)

**Comment by dummylabs** [comment]
Should be fixed in 0.6.2
