### ISSUE TITLE
How to avoid searching on files at /config/custom_components?

### ISSUE THREAD

**Issue by felipecrs** [dummylabs/thewatchman#134]
I have a bunch of false positives there. I don't need the scan to be performed in this folder.

**Comment by teskanoo** [comment]
![image](https://github.com/dummylabs/thewatchman/assets/65863752/cb09735c-e105-4a4d-aab8-72a8afc233cd)

Add the folder into this comma-separated list

![image](https://github.com/dummylabs/thewatchman/assets/65863752/578cfd47-5259-4c22-a1fd-1b351824be94)

**Comment by felipecrs** [comment]
With an asterisk. That's the catch. Thank you.
