### ISSUE TITLE
utf-8' codec can't decode byte 0xb0 in position 37

### ISSUE THREAD

**Issue by Mariusthvdb** [dummylabs/thewatchman#138]
This is happening while running the HA beta 2024.7.0b3
and the Main fix for the [raised blocking call](https://github.com/dummylabs/thewatchman/issues/137) which I downloaded and restarted just now

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.watchman.utils
Bron: custom_components/watchman/utils.py:291
integratie: Watchman (documentatie, problemen)
Eerst voorgekomen: 13:24:03 (15 gebeurtenissen)
Laatst gelogd: 13:24:05

Unable to parse /config/._device_tracker.yaml: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte. Use UTF-8 encoding to avoid this error
Unable to parse /config/._recorder.yaml: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte. Use UTF-8 encoding to avoid this error
Unable to parse /config/._customizer.yaml: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte. Use UTF-8 encoding to avoid this error
Unable to parse /config/._frontend.yaml: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte. Use UTF-8 encoding to avoid this error
Unable to parse /config/custom_components/._services.yaml: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte. Use UTF-8 encoding to avoid this error
```

**Comment by dummylabs** [comment]
Thanks for the report. It looks a bit weird that all these errors refer to the same position in different files.
BTW, all these files are hidden, i.e. they will not be picked up by Home Assistant. Are you sure those have UTF-8 format and have no issues from Home Assistant side? Anyway it's a good catch, we need to add an additional check here.

1. Can you confirm that this error doesn't occur when running W 0.6.2 against HA 2024.7.*?
2. Can you please provide one of those yaml files (without personal information) for analysis?

**Comment by Mariusthvdb** [comment]
tbh, I dont have a clue what you mean when you mention 'one of those yaml files'?

I did not see the errors being logged after another restarts maybe it was a one time fluke?

**Comment by Mariusthvdb** [comment]
cant this be caused by the changes that were recently idoen?
https://github.com/dummylabs/thewatchman/commit/18b5d688f12d3c3f3c2d00e1cf10c0c6acb3c561

**Comment by Mariusthvdb** [comment]
Wait, I decided to check those file names with Studio Code Server in HA directly, and not the file manager on the Mac over Samba.

it appears these files Do exist:

![IMG_4837](https://github.com/dummylabs/thewatchman/assets/33354141/59c502bc-9aae-49c0-92fb-84f337232870)

no clue yet what they do or when/why created but at least there’s is some progress 

If these files are legit and always there it would indeed be nice to be able to excluded them from the configuration with an option.

**Comment by Mariusthvdb** [comment]
now what I believe happened, is tha my default editor BBEdit creates those files upon opening/editing, and doesnt remove them when ready/saving/closing those files.

Also, my SMB add-on hid those files by vetoing them, so I couldn't see them in the Finder, but the VSCode add-on was not filtering these files.

Remians the why: why did this start to happen lately, Ive been using BBEdit since forever.... an updated was installed, maybe some settings changed, although I checked and couldnt really find an obvious option to control that.

Right now, Ive manually deleted all those files, and set Watchman to ignore `._*` and hope that is the right setting.

Otoh, in hindsight, it might be a good idea to have some checker keep an eye out for those hidden file creations/remnants
