### ISSUE TITLE
File not being updated as expected

### ISSUE THREAD

**Issue by kaizersoje** [dummylabs/thewatchman#14]
I am not sure what's happening here. I created a report and removed some entities highlighted in the report.

I recreated the report and those entities are still showing up in the file. I can see that the Report created timestamp in the footer of the file is being updated but do not see the contents being updated.

**Comment by dummylabs** [comment]
When you change a configuration file, watchman has to parse it again. Parsing is done automatically after Home Assistant restart or when any part of yaml configuration was reloaded, i.e. user clicks an item under "YAML configuration reloading" section in Configuration->Settings menu.

Parsing can be an expensive operation e.g. on a single-board computer like Raspberry Pi, so it is not performed for each report by default. However, you can force parsing by adding `parse_config: true` to the service parameters.
