### ISSUE TITLE
History graph error

### ISSUE THREAD

**Issue by Krapulax79** [dummylabs/thewatchman#142]
![Screenshot_20240710_182117_io homeassistant companion android](https://github.com/dummylabs/thewatchman/assets/83902307/fd5d8267-3097-490b-a0bf-028112966f57)

**Comment by ildar170975** [comment]
Where is an error here?
If you mean a weird accuracy - this could be how Ha core or frontend process data.

https://github.com/home-assistant/frontend/issues/18982
https://github.com/home-assistant/core/issues/118509

![289289882-036ca104-f23e-4e9d-b020-a220e3c28733](https://github.com/dummylabs/thewatchman/assets/71872483/6c9ee85a-269e-47a4-ab1d-e4388b0cd953)
