### ISSUE TITLE
Updates > 0.6.1 possible even HA Core version does not match minimum required versions (hacs.json not maintained properly)

### ISSUE THREAD

**Issue by bcutter** [dummylabs/thewatchman#144]
Updating watchman from 0.6.1 to 0.6.3 breaks the integration:

![grafik](https://github.com/user-attachments/assets/1c589677-64ce-412b-a14f-81ea242eeb7b)

```
Logger: homeassistant.setup
Source: setup.py:347
First occurred: 18:38:17 (1 occurrences)
Last logged: 18:38:17

Unable to prepare setup for platform watchman.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).
```

The update was offered through HACS. While https://github.com/dummylabs/thewatchman/blob/v0.6.3/requirements.txt notes HA Core 2024.6.4 is required, the necessary information in https://github.com/dummylabs/thewatchman/blob/v0.6.3/hacs.json unfortunately is missing - leading to an update offered to systems which don't fulfil the necessary requirements.

Please maintain the hacs.json file properly.

**Comment by dummylabs** [comment]
Will be fixed in 0.6.4
