### ISSUE TITLE
Detected blocking call to open inside the event loop 

### ISSUE THREAD

**Issue by jaip1234** [dummylabs/thewatchman#146]
Extract from log file: 

WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'watchman' at custom_components/watchman/utils.py, line 258: for i, line in enumerate(open(yaml_file, encoding="utf-8")): (offender: /config/custom_components/watchman/utils.py, line 258: for i, line in enumerate(open(yaml_file, encoding="utf-8")):), please create a bug report at https://github.com/dummylabs/thewatchman/issues

**Comment by dummylabs** [comment]
Not reproducible in 0.6.3
