### ISSUE TITLE
Should update instructions readme - Services Tab was renamed to Actions in 2024.8

### ISSUE THREAD

**Issue by gaitskell** [dummylabs/thewatchman#149]
Services was renamed to Actions in 2024.8

[https://www.home-assistant.io/blog/2024/08/07/release-20248/#goodbye-service-calls-hello-actions- 12](https://www.home-assistant.io/blog/2024/08/07/release-20248/#goodbye-service-calls-hello-actions-)

Thank you for your very useful software

**Comment by dummylabs** [comment]
Fixed, thanks. Some work is still required to update the Watchman UI itself, including changing the names of the sensors without breaking backward compatibility where possible. This will be targeted for the next version.
