### ISSUE TITLE
The Watchman doesn't detect unavailable entities

### ISSUE THREAD

**Issue by pniewiadowski** [dummylabs/thewatchman#150]
The Watchman doesn't detect unavailable entities. 
Right now, when I go to Entities in Home Assistant and filter for unavailable Status of entities I have like 80 unavailable. 
![image](https://github.com/user-attachments/assets/33b02733-4537-4cec-bb40-509dae4f5d5f)

The Watchman sees only half of it, 41 items:
![image](https://github.com/user-attachments/assets/5a6e2b12-e55e-41b4-9786-8f58693f5e71)

What could be the reason?

**Comment by Hiekkaharju** [comment]
Watchman only reports entities that are used somewhere. On dashboard, in automations or in templates etc. Not every non-interesting entity some integration creates to it's devices.
