### ISSUE TITLE
Entity in Tuya-Local file erroneously included in report

### ISSUE THREAD

**Issue by reef-actor** [dummylabs/thewatchman#151]
I have the tuya-local integration installed.
In the Watchman report I see the following notification:

```
climate.current_humidity [missing]
electriq_desd9lw_dehumidifier.yaml
```
I don't have an entity called climate.current_humidity or a dehumidifier.
The entity name exists on [line 92 of the file in tuya-local](https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/electriq_desd9lw_dehumidifier.yaml#L92).

**Comment by reef-actor** [comment]
I have avoided this issue by adding `**/config/custom_components/**` to Ignored files. Would it make sense to ignore this path by default?
Perhaps the description by the Ignored files field could be modified to mention that it supports globs and it supports ignoring folders?

**Comment by felipecrs** [comment]
I believe it would make a lot of sense to ignore such path by default.

**Comment by dummylabs** [comment]
Right, this will also help with #130

**Comment by dummylabs** [comment]
Following items will be set as default ignored files for new installations of Watchman 0.6.4
`*/blueprints/*, */custom_components/*, */esphome/*`

**Comment by felipecrs** [comment]
@dummylabs, to be honest, it makes sense to scan the *.yaml files in ESPHome.

That's because we can call Home Assistant actions within ESPHome devices. I use this a lot, for example I have a wall socket in which the button will toggle my Home Assistant fan entity if I long press.
