### ISSUE TITLE
ignore scenes that are not defined

### ISSUE THREAD

**Issue by hugalafutro** [dummylabs/thewatchman#16]
Hi,
you can create scenes "on the fly" (https://www.home-assistant.io/integrations/scene/#applying-a-scene-without-defining-it) during an automation and and they do not exist outside the context of the automation, however watchman will keep reporting them as missing.

**Comment by dummylabs** [comment]
So far there are no means for watchman to distinguish between permanent scenes and provisional ones, it just checks the status of all entities from configuration files which name starts with `scene.`. The best you can do is to add temporal scenes (or the whole `scene` domain) as exceptions with **Ignored entities and services** UI option.

**Comment by hugalafutro** [comment]
Thanks I added the entities to exclusions. Just thought it'd be nice if they were ignored by default, seeing as they sort of do not exist by design.
