### ISSUE TITLE
Watchman Updated sensor Invalid Timestamp

### ISSUE THREAD

**Issue by Daneish** [dummylabs/thewatchman#17]
I have noticed a small bug with the timestamp formatting of the sensor.watchman_last_updated entity when using the iOS / iPadOS Home Assistant apps.

When viewing any lovelace dashboards with the watchman_last_updated entity displayed, the entity would show as `Invalid timestamp` and I would get the following error in the HA logs:
`ERROR (MainThread) [frontend.js.latest.202203010] https://[my-HA-URL]/frontend_latest/92deadc4.js:258:77216 RangeError: number argument must be finite`

The errors do not occur on Windows with Edge.

The error did not occur for any of my other device_class: timestamp entities. 
Looking at the formatting of my working entity it is using (what I have just learnt is) the ISO 8601 format of `YYYY-MM-DDTHH:MM:SS+UTCOFFSET`, e.g. `2022-03-03T14:12:17+00:00`

The watchman_last_updated sensor is substituting the T with a space character, e.g. `2022-03-10 17:33:25.133995+11:00`

I found that the [HA templating documentation](https://www.home-assistant.io/docs/configuration/templating/#time) reference this issue:

> If your template is returning a timestamp that should be displayed in the frontend (e.g., as a sensor entity with device_class: timestamp), you have to ensure that it is the ISO 8601 format (meaning it has the “T” separator between the date and time portion). Otherwise, frontend rendering on macOS and iOS devices will show an error. 

I'm running:
Watchman: 0.5.0 (through HACS)
Home Assistant Core: 2022.3.2
Supervisor: 2022.03.2
Home Assistant OS: 7.4
Hardware: Raspberry Pi 4b

Would the date format of the sensor be something you would be happy to change? Let me know if there is any other information or testing I can help with, and thanks very much for a great integration!

Edit: The above documentation suggests enforcing iso conversion with the function `isoformat()`. That didn't work for me with the watchman sensor, but for testing, I created the below template sensor which did not generates the errors:
`- name: "Watcher Test"`
`state: "{{ as_timestamp(states('sensor.watchman_last_updated')) | timestamp_custom('%Y-%m-%dT%H:%M:%S%z') }}"`
`device_class: timestamp`

**Comment by dummylabs** [comment]
Thank you for such a deep research, I'll investigate it and add fix to an upcoming release.

**Comment by Daneish** [comment]
Thanks very much. And thanks again for a great integration, it has helped me find many loose ends I didn't know I had!

**Comment by Daneish** [comment]
Alternatively, if it’s possible to add a `unique_id` to the Watchman sensors, that would allow us to implement HA‘s new `Ignore` feature to remove the problematic sensor from the default dashboard. Although, I assume that is probably a non-trivial task.

**Comment by dummylabs** [comment]
Yep, current codebase uses plain `set_state` API calls as a quick way to manually create entities and their attributes instead of using special API classes provided by HA. Among other useful things, like aggregation of multiple entities under a device or service, these classes provide entities with the `unique_id`. There are some plans to refactor this part of the code as soon as I have a bit of spare time.

**Comment by Daneish** [comment]
Nice! Looking forward to it when the time comes!

**Comment by dummylabs** [comment]
Should be fixed in 0.5.2, please check.

**Comment by Daneish** [comment]
I can confirm it’s now displaying correctly and no longer generating an error. Thanks very much!
