### ISSUE TITLE
Detected blocking call to iglob - HA crashed

### ISSUE THREAD

**Issue by dawiinci** [dummylabs/thewatchman#185]
Logger: homeassistant.util.loop
Quelle: util/loop.py:136
Erstmals aufgetreten: 05:41:39 (2 Vorkommnisse)
Zuletzt protokolliert: 05:41:39

Detected blocking call to iglob with args ('/Users/server/Steuerung/homeassistant-config/**/*.yaml',) inside the event loop by custom integration 'watchman' at custom_components/watchman/utils.py, line 160: for filename in glob.iglob(folder, recursive=True): (offender: /Users/server/Steuerung/homeassistant-config/custom_components/watchman/utils.py, line 160: for filename in glob.iglob(folder, recursive=True):), please create a bug report at https://github.com/andreasbrett/thewatchman/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#iglob Traceback (most recent call last): File "/Users/server/Steuerung/homeassistant/bin/hass", line 8, in <module> sys.exit(main()) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/runner.py", line 130, in setup_and_run_hass return await hass.async_run() File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 534, in async_run await self.async_start() File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 587, in async_start self.bus.async_fire_internal(EVENT_HOMEASSISTANT_STARTED) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 1587, in async_fire_internal self._hass.async_run_hass_job(job, event) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 949, in async_run_hass_job hassjob.target(*args) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 1448, in __call__ self.hass.async_run_hass_job(self.listener_job, event) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 952, in async_run_hass_job return self._async_add_hass_job(hassjob, *args, background=background) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 767, in _async_add_hass_job task = create_eager_task( File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/Users/server/Steuerung/homeassistant-config/custom_components/watchman/__init__.py", line 273, in async_on_home_assistant_started await parse_config(hass, reason="HA restart") File "/Users/server/Steuerung/homeassistant-config/custom_components/watchman/__init__.py", line 350, in parse_config entity_list, service_list, files_parsed, files_ignored = await parse( File "/Users/server/Steuerung/homeassistant-config/custom_components/watchman/utils.py", line 252, in parse for yaml_file, ignored in get_next_file(folders, ignored_files): File "/Users/server/Steuerung/homeassistant-config/custom_components/watchman/utils.py", line 160, in get_next_file for filename in glob.iglob(folder, recursive=True):
Detected blocking call to scandir with args ('/Users/server/Steuerung/homeassistant-config/',) inside the event loop by custom integration 'watchman' at custom_components/watchman/utils.py, line 160: for filename in glob.iglob(folder, recursive=True): (offender: /opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/glob.py, line 170: with os.scandir(arg) as it:), please create a bug report at https://github.com/andreasbrett/thewatchman/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#scandir Traceback (most recent call last): File "/Users/server/Steuerung/homeassistant/bin/hass", line 8, in <module> sys.exit(main()) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/runner.py", line 130, in setup_and_run_hass return await hass.async_run() File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 534, in async_run await self.async_start() File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 587, in async_start self.bus.async_fire_internal(EVENT_HOMEASSISTANT_STARTED) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 1587, in async_fire_internal self._hass.async_run_hass_job(job, event) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 949, in async_run_hass_job hassjob.target(*args) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 1448, in __call__ self.hass.async_run_hass_job(self.listener_job, event) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 952, in async_run_hass_job return self._async_add_hass_job(hassjob, *args, background=background) File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/core.py", line 767, in _async_add_hass_job task = create_eager_task( File "/Users/server/Steuerung/homeassistant/lib/python3.13/site-packages/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/Users/server/Steuerung/homeassistant-config/custom_components/watchman/__init__.py", line 273, in async_on_home_assistant_started await parse_config(hass, reason="HA restart") File "/Users/server/Steuerung/homeassistant-config/custom_components/watchman/__init__.py", line 350, in parse_config entity_list, service_list, files_parsed, files_ignored = await parse( File "/Users/server/Steuerung/homeassistant-config/custom_components/watchman/utils.py", line 252, in parse for yaml_file, ignored in get_next_file(folders, ignored_files): File "/Users/server/Steuerung/homeassistant-config/custom_components/watchman/utils.py", line 160, in get_next_file for filename in glob.iglob(folder, recursive=True):

**Comment by dummylabs** [comment]
Please check if you have the latest version of Watchman. This error should have been resolved a few versions ago.
