### ISSUE TITLE
Watchman Report - State missing

### ISSUE THREAD

**Issue by Dzoker2** [dummylabs/thewatchman#186]
What happened?

In Home Assistant, Watchman keep reporting this 4 lines

| alert.signature_id | missing | .storage/crowdsec/config/hub/parsers/s01-parse/crowdsecurity/suricata-logs.yaml:62
| alert.rev | missing | .storage/crowdsec/config/hub/parsers/s01-parse/crowdsecurity/suricata-logs.yaml:64 |
| alert.signature | missing | .storage/crowdsec/config/hub/parsers/s01-parse/crowdsecurity/suricata-logs.yaml:66
| alert.severity | missing | .storage/crowdsec/config/hub/parsers/s01-parse/crowdsecurity/suricata-logs.yaml:68

What did you expect to happen? - I guess not to see the reported

How can we reproduce it (as minimally and precisely as possible)? - Run Watchman

Crowdsec version - 1.6.3
OS version - 14
HA Core - 2024.12.3

I did report this also to crowdsec (https://github.com/crowdsecurity/crowdsec/issues/3345)

One of the responses was:
"From what I can see watchman should not be monitoring these files as these files are not something to do with Home Assistant but our own software.

So I would suggest to use the ignore files options in watchman and add .storage/crowdsec/config/* if possible as these files cant be modified to have home assistant / watchman attributes since it will fail our schema validation."

but Watchman is  asking for "comma-separated list of entities and actions" to be excluded from tracking, not the path

Thank you

**Comment by dummylabs** [comment]
>  it will also parse the hidden .config folder

I just realized that Watchman should not look into any folders within `.storage` besides lovelace. I will check if there is a bug. Nevertheless, the solution described above should work.

**Comment by Dzoker2** [comment]
Hi, thank s for your fast answer. The Parse UI was already unchecked when the 4 lines were showing. Adding */crowdsec/* did the trick. 

I now have the following in the ignored files:
*/blueprints/*, */custom_components/*, */esphome/*, */crowdsec/*

I restarted HA and ran the watchman report again.. the 4 lines from crowdsec are gone now

Thank you

**Comment by Dzoker2** [comment]
@dummylabs Where can I add a suggestion?
