### ISSUE TITLE
Entities' states are in string format

### ISSUE THREAD

**Issue by fabricioavil** [dummylabs/thewatchman#19]
Hi,

I noticed the states on:

sensor.watchman_missing_entities
and
sensor.watchman_missing_services

are in str format instead of int. It causes problems, for example, when creating automations, we need to convert the state to int.

So, could the state be already in int format?

Thank you.

**Comment by dummylabs** [comment]
Hey @fabricioavil, I believe this the standard behaviour for all integration sensors. I've checked several integrations which provide numeric sensors (github sensor, glances, etc), they all require string to int type casting. The following template returns type error `{{ states.sensor.glances_addons_free.state > 0 }}` whereas the state value is 40.0.
You may also want to check this forum post: https://community.home-assistant.io/t/numeric-sensor-values-are-always-strings/318333

**Comment by fabricioavil** [comment]
Hi,

I checked directly on HASS as you mentioned and indeed the others are reported as str.

But what is interesting is when I customize the entity

in configuration.yaml:
```
homeassistant:
  customize: !include customize.yaml
```

in customize.yaml:
```
sensor.watchman_missing_services:
  templates:
    icon_color: 'if (state  >= 1) return ''red'';'
```

it doesn't work, but for another entities it works, example:
```
sensor.hacs:
  templates:
    icon_color: 'if (state >= 1) return ''red'';'
```

so, when I saw in the developer tools that the state wasn't int I thought it was the problem, but as you said and I saw now, sensor.hacs also has the state as str.

Do you think this error customizing the entities can be something in Watchman? If not, please feel free to close the issue.

Thank you!

**Comment by ondras12345** [comment]
All states in Home Assistant are strings.
https://www.home-assistant.io/docs/configuration/state_object/
Attributes, on the other hand, can have different data types.

**Comment by dummylabs** [comment]
@fabricioavil It looks weird, but so far I have no idea why does customisation work with HACS sensor this way. Frankly, there is a room for improvements in how watchman works with HA sensors internally (e.g. use of special entity classes instead of simple set_state), they require some complex refactoring of sensor part and will not guarantee the success. 
The issue will be updated if I reach any progress on that.
