### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by SteveRMann** [dummylabs/thewatchman#24]
Suggestion- how about an _ignore_ list?

For example, in an ESPHome device I have scripts, and to call one I use _script.execute_
Problem is, Watchman thinks that this is an entity.

**Comment by dummylabs** [comment]
It is already here: go to Configuration->Device&Services->Watchman->"Ignored entities and services". There you can add either `script.execute` to ignore single entity or `script.*` to ignore all entities which start from "script".

**Comment by SteveRMann** [comment]
Thanks. I didn't read the manual to the end.....
