### ISSUE TITLE
Watchman pick string as entity when inside match or search template functions

### ISSUE THREAD

**Issue by clempat** [dummylabs/thewatchman#31]
I have some template sensor https://github.com/clempat/home-assistant/blob/main/configurations/heating/heating.yaml#L16 

Like 
```
        {%- set data = namespace(radiator_ids=[]) -%}
        {%- for switch in states.switch -%}
          {%- if switch.entity_id is match('switch.heating') and switch.state in ['unavailable', 'unknown'] -%}
            {%- set data.radiator_ids = data.radiator_ids + [switch.entity_id] -%}
          {%- endif -%}
        {%- endfor -%}
        {{ data.radiator_ids | list | count }}
```

or
```
        {%- macro getRoomTemperature(room) -%}
            {%- set data = namespace(temperatures=[]) -%}
            {%- set temperature_entities =  expand(area_entities(room)) | selectattr('attributes.device_class', 'eq', 'temperature') | rejectattr('state', 'in', ['unavailable', 'unknown']) -%}
            {%- for entity in temperature_entities -%}
            {%- set device_id = device_id(entity.entity_id) -%}
              {%- if device_attr(device_id, 'model') is search('weather', ignorecase=True) or device_attr(device_id, 'model') is search('sensor.ht', ignorecase=True) %}
                  {%- set data.temperatures = data.temperatures + [entity.state] -%}
              {%- endif -%}
            {%- endfor -%}
            {{ data.temperatures | map('float') | average | round(1) }}
        {%- endmacro -%}
        {{ getRoomTemperature("Salon") }}
```

I get from watchman: 
```
| switch.heating                 | missing | configurations/heating/heating.yaml:16,25                    |
| sensor.ht                      | missing | configurations/heating/heating.yaml:63,79,95,111,127,143,159 |
|                                |         | ,175,191,207,223,239  
```
I am uncertain if it makes sense to consider those as entity as they are in those templates function which allow having partial name.

**Comment by dummylabs** [comment]
Hey @clempat, as documentation mentions, watchman cannot determine if `switch.heating` is a real entity or just a part of a template. It assumes that all text sequences, encountered in configuration files, which start from `switch.` _can be_ a real entity. To validate this hypothesis, watchman requests the state of `switch.heating` from the HA. If nothing is returned, watchman marks this entity as missing in the report.
To exclude these false positives from the report one can use "Ignored entities and services" setting which supports wildcards as well. Hope this helps.

**Comment by clempat** [comment]
Thanks, sorry I should have better check the documentation. It is already an awesome tool. It helped me a lot to discover some typo I never saw.
