### ISSUE TITLE
Watchman not seeing some switch entities

### ISSUE THREAD

**Issue by MikeGuest** [dummylabs/thewatchman#33]
I'm getting reports of a missing ewelink device which is not missing

| switch.10009d2045              | missing | lovelace/tiles/david.yaml:24                                 |
| switch.10009d1d84              | missing | lovelace/tiles/david.yaml:31   

![Screenshot from 2022-04-21 18-46-00](https://user-images.githubusercontent.com/12844043/164520199-5e15db71-dfe6-49e6-948c-d1c8c8955ab1.png)

**Comment by MikeGuest** [comment]
closing as cannot now reproduce

**Comment by MikeGuest** [comment]
apologies

**Comment by dummylabs** [comment]
The reason might be that entities were not available when report was created and became available later on.
