### ISSUE TITLE
Installed version 0.5.2 - new version 0.5.0

### ISSUE THREAD

**Issue by Pirol62** [dummylabs/thewatchman#39]
something is wrong with the release numbering.
A pic says more then 1000 words:
![image](https://user-images.githubusercontent.com/48820003/165452311-4ed59e22-bc46-48ff-839c-fafc22f1d9ea.png)
![image](https://user-images.githubusercontent.com/48820003/165452443-18f6f6ca-3357-4d71-ac22-c692142f4323.png)

**Comment by dreimer1986** [comment]
Looks like a revert for me. The version was removed from repository. Maybe because of the mentioned bugs you can find before yours.

**Comment by Pirol62** [comment]
Ok, if this is the case, I've liked to get some info about that ;-)

**Comment by Kpapadak1** [comment]
Seeing the same issue. It is very confusing. Was this a revert? Can we get a confirmation?

**Comment by dummylabs** [comment]
This is a problem on the github side, the same issue was reported for HA core repository.
The most recent version is 0.5.2 and currently it is not available on github by some unknown reason.

**Comment by dummylabs** [comment]
Found a workaround, now 0.5.2 should be available again.

**Comment by dreimer1986** [comment]
Well, now we have a new one of that kind... It fell back to 0.5.1 as newest version this time.

![image](https://user-images.githubusercontent.com/29841368/166881979-98a6d6b9-e9d9-480a-8451-c39e7261992e.png)

**Comment by rubicon** [comment]
See issue #43, I think he might be barking up the right tree.
