### ISSUE TITLE
Watchman sensors are not linked to the config entry

### ISSUE THREAD

**Issue by bieniu** [dummylabs/thewatchman#44]
Watchman sensors are not linked to the config entry, they do not support entity registry like other integrations.

![image](https://user-images.githubusercontent.com/478555/167250055-dddbe476-9f5a-4353-a755-650133685c4d.png)

**Comment by dummylabs** [comment]
Hey @bieniu, support for this is on the roadmap.

**Comment by dummylabs** [comment]
Fixed in v0.6.0
