### ISSUE TITLE
Not reporting a device as unavailable

### ISSUE THREAD

**Issue by jake404** [dummylabs/thewatchman#45]
I have a door contact that is currently unavailable because of low battery, however, Watchman is not reporting this device to be unavailable. Is Watchman limited to certain types of devices?

**Comment by dummylabs** [comment]
Hey @jake404, in order to be reported by watchman, your device (entity) ID should be referenced by one of your yaml configuration files. If that is true, what exactly ID is?

**Comment by jake404** [comment]
Ok, I misunderstood how Watchman looked at entities. I thought it looked at all entities, not just the ones referenced in the configuration files.
