### ISSUE TITLE
Watchman integration not found

### ISSUE THREAD

**Issue by kongjudas** [dummylabs/thewatchman#47]
I have installed via HACS, rebooted, emptied the buffer and tried to find the integration with no luck. I have tried to roll back one version, but still no cigar. I didn't use it between some updates, so I'm not sure where things got wrong. The earlier versions worked perfect.
<img width="395" alt="Skjermbilde 2022-05-10 kl  18 43 24" src="https://user-images.githubusercontent.com/55403016/167680202-b315e1f5-6ee1-47d3-baa1-902739090771.png">
k

**Comment by yuvalabou** [comment]
Same here

**Comment by grastraa** [comment]
+1

**Comment by Clam58** [comment]
+2

**Comment by micium** [comment]
+3

**Comment by dummylabs** [comment]
I've tested installation just now on a fresh Home Assistant and HACS. Watchman was not shown on "Set up a new integration" page until I emptied my browser cache. For Google Chrome the easiest way is to:
1. Press F12 to open developer console
2. Right click on "Reload this page" button and select "Empty cache and hard reload" from context menu.

**Comment by Clam58** [comment]
I was using the iOS app, so shut that down and used a browser which worked for me

**Comment by dummylabs** [comment]
Hey @kongjudas, @yuvalabou if the issue still exists, try to reinstall integration via HACS (three dots menu->Redownload) and select version 0.5.3. Don't forget to restart HA and empty browser's cache to be on the safe side.

Another way to check if integration was installed by HACS is System Health screen (Settings->System->System Health)
[![Open your Home Assistant instance and show health information about your system.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)

I'll close the issue, feel free to add comments if further support is required.
