### ISSUE TITLE
telegram example in Readme.md needs quotes

### ISSUE THREAD

**Issue by hugalafutro** [dummylabs/thewatchman#49]
I spent last 30 minutes trying to open PR, but I have to concede with the realization I'm too old and stupid as github kept forcing me to compare branches or some mumbo jumbo, I just wanted to submit PR edit for 1 bloody text file, but I digress.

Anyways, you need to add qutoes to the example @ https://github.com/dummylabs/thewatchman#send-report-via-telegram-bot
so instead of `Notification service data: {parse_mode:html}` it says `Notification service data: {"parse_mode":"html"}` otherwise you'll get 
![image](https://user-images.githubusercontent.com/30209689/170958929-ccb347f9-7dbc-44e7-a69c-0c9ff257f55f.png)
when using the example as it is.

**Comment by dummylabs** [comment]
Correct, docs fixed, thank you!
