### ISSUE TITLE
Documentation markdown is incorrect

### ISSUE THREAD

**Issue by EDelsman** [dummylabs/thewatchman#52]
The readme example on how to create markdown for missing services is no longer correct. It iterates over a services attribute, which is now called entities. (That or the attribute got renamed by mistake)

**Comment by curt7000** [comment]
Does anyone know how to correct this?

**Comment by ondras12345** [comment]
https://github.com/dummylabs/thewatchman/pull/59

**Comment by curt7000** [comment]
> #59

Working now!  Thank you!

**Comment by dummylabs** [comment]
Should be fixed together with #112 and #93 in 0.6.2
