### ISSUE TITLE
Configuration Examples Included in Missing Entities

### ISSUE THREAD

**Issue by crawshaws** [dummylabs/thewatchman#56]
The configuration files I have in my HA instance have "example" keys which have values that do not exist in my instance (as they are used purely as an example)

![image](https://user-images.githubusercontent.com/9270064/179794872-f7741964-a15d-445b-ad93-27a8233b3c0d.png)

For the "camera.front_door" entity, this is referring to this example:

![image](https://user-images.githubusercontent.com/9270064/179795054-783b9e9f-62eb-4911-b1a2-e80e2290b1b1.png)

Is there a way to omit scanning certain configuration keys as well as the entities themselves?

**Comment by Hiekkaharju** [comment]
I just want to support the idea of making this improvement. Examples seem to be a common source for false positives. E.g. also the scheduler-component (hacs) uses examples in it's services.yaml and each of them that represents a place where an entity should be given causes a false positive in Watchman .  Sure they can be configured as ignored, by each user of Watchman, but automatically ignoring lines starting with "example:" in Watchman would be a more user frindly solution.

**Comment by dummylabs** [comment]
New installations of Watchman (0.6.4 and latter) will have `custom_components`, `blueprints` and `esphome` dirs in ignored items list by default.
