### ISSUE TITLE
Issue after HA 22.10.1 update

### ISSUE THREAD

**Issue by sheminasalam** [dummylabs/thewatchman#61]
Getting the following error in logs with component not loaded

```
Logger: homeassistant.setup
Source: setup.py:192
First occurred: 6:43:03 AM (2 occurrences)
Last logged: 6:43:07 AM

Setup failed for custom integration watchman: Unable to import component: cannot import name 'PrettyTable' from 'prettytable' (/usr/local/lib/python3.10/site-packages/prettytable/__init__.py)
```

**Comment by dummylabs** [comment]
I've just tested installation on HA 22.10.3 with the latest version of HACS, it ran flawlessly. 
It may be that something went wrong during installation, e.g. PrettyTable repository was offline by some weird reason. I'd recommend to do the following:
1. Update HACS to the latest version
2. Remove Watchman from HACS, restart HA and ensure there is no folder `watchman` in` /config/custom_components` (should be deleted automatically by HACS, if not - remove it)
3. Install Watchman via HACS, restart HA and add component via Device&Services->Add Integration.

If the issue remains afterwards, feel free to reopen this ticket, thanks.

**Comment by pastukhov** [comment]
I have container installation of HA and RO container root.
Same error for me and i see attempt to install python libraries to `/root/.local`
```
2023-12-13 14:41:49.399 ERROR (SyncWorker_17) [homeassistant.util.package] Unable to install package prettytable==3.0.0: ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/root/.local'
```

**Comment by pastukhov** [comment]
I have run HA with  -e PYTHONUSERBASE=/config  and error is gone
