### ISSUE TITLE
first and subsequent runs always fail

### ISSUE THREAD

**Issue by jebeke65** [dummylabs/thewatchman#62]
Hi,

I always get error(s) when I try to run the report.

**I'm calling this service :**
service: watchman.report
data:
  send_notification: false

**I'm using the default settings**

**These are the errors I get :**
[139721525891696] Error handling message: Unknown error (unknown_error)
9:00:42 AM – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at 8:10:28 AM and shows up 12 times
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'services_missing'
9:00:42 AM – (ERROR) Watchman (custom integration) - message first occurred at 8:10:28 AM and shows up 12 times
Unexpected error fetching Watchman data: Service list not found
9:00:41 AM – (ERROR) Watchman (custom integration) - message first occurred at 8:10:28 AM and shows up 12 times
Error setting up entry Watchman for sensor
8:58:52 AM – (ERROR) helpers/entity_component.py - message first occurred at 8:15:27 AM and shows up 63 times
Error setting up entry Watchman for watchman
8:58:51 AM – (ERROR) Watchman (custom integration) - message first occurred at 8:09:58 AM and shows up 64 times

Tx for taking a look at the above.

Jan

**Comment by dummylabs** [comment]
It seems like a HA/HACS configuration problem. Try to update HACS and HA to the latest version, then remove and install Watchman again as suggested here: https://github.com/dummylabs/thewatchman/issues/61
Please let me know on the results, thanks!
