### ISSUE TITLE
Support for pyscript

### ISSUE THREAD

**Issue by adwuk** [dummylabs/thewatchman#63]
I have been using pyscript for my automations, as well as YAML. I thought that I would mention that watchman does a pretty good job of scanning python files and detecting problems as well.  Essentially the easiest way to use pyscript is to put all your python files into the /config/pyscript directory.  I have added the following to __init__.py to get it working. You may want to provide it as an option for others.

```
def get_included_folders(hass):
...
    folders.append(os.path.join(hass.config.config_dir, "pyscript/*.py"))
```

The one thing that it doesn't cope with is pyscript's ability to refer to attributes in the same definition, e.g. entity.attribute, but other than that, 10/10! Thanks - great utility.

**Comment by dummylabs** [comment]
It is not necessary to modify WM source files - additional scan folders can be added via options dialog.
Python is very flexible and feature-rich language so I'm pretty sure we cannot fully support it with WM regular expression rules.
