### ISSUE TITLE
ESPHome False Positive

### ISSUE THREAD

**Issue by kernelpanic85** [dummylabs/thewatchman#65]
I think Watchman may be incorrectly reporting missing entities in my ESPHome configs.  The following are the errors reported and attached is the yaml config in question.  My switch compiles and is working normally as far as I can tell.

| light.is_on                    | missing | esphome/kitchen-overhead-master.yaml:106,146                 |
| light.dim_relative             | missing | esphome/kitchen-overhead-master.yaml:109,149           

[kitchen-overhead-master.txt](https://github.com/dummylabs/thewatchman/files/10013874/kitchen-overhead-master.txt)

**Comment by filmgarage** [comment]
You may want to add the esphome directory to the ignored files in the Watchman configuration:
Settings > Devices & Services > Integrations > Watchman > Configure (scroll down)
You would have to add `/config/esphome/*` to the list (comma seperated if you add more than one)

**Comment by kernelpanic85** [comment]
Thanks, not a bad idea. Though is Watchman supposed to provide an accurate evaluation of ESPHome configs?

**Comment by m1dst** [comment]
I find mine is doing the same with the call to internal esphome scripts.  So the script is never going to be available to HA as it is just an internal function.   I'll exclude the directory for now.

**Comment by dummylabs** [comment]
New installations of Watchman (0.6.4 and latter) will have `esphome` dir in ignored items list by default.
