### ISSUE TITLE
Feature request -  Know where an entity or service is used -

### ISSUE THREAD

**Issue by RASBR** [dummylabs/thewatchman#66]
Hello,
This is really great, but I think it would be even greater if the user can use it to know where an entity or service is used?

Thank you
R.S

**Comment by filmgarage** [comment]
If you add the Lovelace card to your UI you can hover over the file name where an orphaned entity is located and the pop-up will even show the line number in the file. Or is that not what you are looking for?

**Comment by filmgarage** [comment]
Here is an example:

![Scherm­afbeelding 2023-02-05 om 23 38 33](https://user-images.githubusercontent.com/30559371/216849970-c3611d87-f098-4545-8570-4f0f41edc943.png)

Hovering your mouse over the word automations.yaml shows this entity was references on the lines 1774, 1781, 1791 and 1804 in automations.yaml

**Comment by RASBR** [comment]
I didn't pause the mouse over before, this is really helpful. 

Thank you very much.
R.S.

**Comment by filmgarage** [comment]
You can hover as long as you like, but nothing will happen I'm afraid... 😂

**Comment by bcutter** [comment]
For sure. That's why building UI relying on features only available on a certain type of devices is... oldschool 😎

**Comment by filmgarage** [comment]
You may want to file a feature request to make these file names "clickable" and show the line number. Personally I prefer repairing these issues on my laptop anyway. It's too cumbersome on my mobile.

**Comment by ProfDrYoMan** [comment]
Line numbers are nice, but do not help a "GUI" only user.
Would it be possible to show the name of the automation that is containing the troublemaker?

**Comment by filmgarage** [comment]
I came across this in the readme section:

"4. To display line numbers in the report just remove `.split(':')[0]` from the card template"

If you do so you don't have to hover over the file name anymore.

**Comment by dummylabs** [comment]
I like the idea to extract automation name from the yaml, although I’m uncertain about its ease of implementation. Added #140
