### ISSUE TITLE
logo with transparency

### ISSUE THREAD

**Issue by filmgarage** [dummylabs/thewatchman#74]
I would love to add a custom logo for dark backgrounds and improve the current logo with transparency, could you provide the current logo source file? Preferably a vector image or alike...

**Comment by dummylabs** [comment]
Thank you, that would be really great. I used an online editor to make quick and dirty icons just to fulfil integration requirements. Will try to find SVG source, but not sure I have it. For the shield icon I've been using: https://materialdesignicons.com/icon/shield-half-full

I should say, I would not mind a new icons/logos re-created from scratch from somebody with better sense of beauty than mine. 😃 

Current icons are available in HA brands repository here: https://github.com/home-assistant/brands/tree/master/custom_integrations/watchman.

Requirements for icons and logos are located here: https://github.com/home-assistant/brands

**Comment by filmgarage** [comment]
Can't say that I am a specialist, but what about this one? I like the shield but maybe we can combine this with the "watch" element: an eye that keeps checking if your config is in good shape...

![Watchman Logo](https://user-images.githubusercontent.com/30559371/214557627-ef996fab-0817-4475-97c8-b2df966fe3be.png)

**Comment by filmgarage** [comment]
Variation 1:

![Watchman Logo var1](https://user-images.githubusercontent.com/30559371/214558797-b1f0089d-b419-4b3d-9a47-b3d7bdf9a007.png)

**Comment by filmgarage** [comment]
Variation 2:

![Watchman Logo var2](https://user-images.githubusercontent.com/30559371/214558888-e410c9f5-8d6b-4bd8-a983-20f688cb21aa.png)

**Comment by filmgarage** [comment]
Or with some color?

![Watchman Logo var4](https://user-images.githubusercontent.com/30559371/214560242-3686e596-eab6-4979-a0e9-91f04f618643.png)

**Comment by filmgarage** [comment]
Shield with typographical elements:

![Watchman logo WM](https://user-images.githubusercontent.com/30559371/214584078-ca561cb2-3481-4277-98f1-28b0b02fe905.png)

**Comment by dummylabs** [comment]
Wow! The last one looks amazing on a bright background!
May I ask you to come up with a landscape logo as well (something like attached below, the typeface and font size is up to you)?

<img width="200" alt="Untitled2" src="https://user-images.githubusercontent.com/4209521/216301735-7dc8487c-03e8-48fe-aabd-1e98809247c8.png">

The logo is normally used on the service info page and its landscape orientation should look just fine there.
<img width="1023" alt="SCR-20230202-ixy" src="https://user-images.githubusercontent.com/4209521/216302768-b70fb54e-0287-4e16-97cd-677e460ef030.png">

Thanks again @filmgarage for the great job!

**Comment by filmgarage** [comment]
I will, I guess we also need a logo for a dark background:

![Watchman White](https://user-images.githubusercontent.com/30559371/216432158-efe02464-b977-4633-80d0-85dd3a32d225.png)

(If you can't see the above logo please change your browser to dark mode)

**Comment by filmgarage** [comment]
This is a suggestion for the logo:

For dark backgrounds:
![WM Logo White](https://user-images.githubusercontent.com/30559371/216436281-f93eb643-2fdf-46de-96b2-55e6eafe825a.png)

And light backgrounds:
![logo_black](https://user-images.githubusercontent.com/30559371/216436344-f2b2e3d9-8b05-4f2e-a483-9df5d2d7cba5.png)

(change your browser for dark to light mode or vice versa to see both versions)

**Comment by filmgarage** [comment]
PR for the icons: https://github.com/home-assistant/brands/pull/4102

Just let me know your preference for the logo and I will finish that as well...

**Comment by filmgarage** [comment]
@dummylabs What do you think about the logo? Do you want any changes?
