### ISSUE TITLE
async_setup_platforms will fail in HA version 2023.3

### ISSUE THREAD

**Issue by pedolsky** [dummylabs/thewatchman#76]
After updating to HA core-2023.0b0, the following warning appeared:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77 
First occurred: 21:49:01 (1 occurrences) 
Last logged: 21:49:01

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for watchman using this method at custom_components/watchman/__init__.py, line 130: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by dummylabs** [comment]
Fixed in 0.6.1.
