### ISSUE TITLE
Will not find errors when reconfiguring integration to exclude files and/or folders

### ISSUE THREAD

**Issue by curt7000** [dummylabs/thewatchman#78]
I am running HA Core 2023.2.1, VENV on Python 3.10.  Integration has been running well for quite some time, thank you!  However, I have some KeyMaster yaml and services that I would like to exclude.  I tried “Configuring” the integration again with the file/folder exceptions but after saving, Watchman no longer identifies known errors that were previously listed and not part of the exception list.  This occurs even after restarting and reloading the integration.

note: I have not removed and attempted to reinstall the integration.

**Comment by filmgarage** [comment]
Maybe you can post the file/folder exception you set up. Otherwise it is going to be very difficult for anyone to help you. ;-)

**Comment by curt7000** [comment]
I've attempted to exclude files by entering:
`*/customize.yaml, */groups.yaml`

For folders, I've attempted to exclude by entering:
`/config/custom_components/*, /config/backup/*`

**Comment by dummylabs** [comment]
According to the report, Watchman found 0 files to parse and 0 files were ignored. My bet is that path to the config directory is not correct. Feel free to reopen this issue if additional details come to light.
