### ISSUE TITLE
After adding file or folder exceptions the integration no longer identifies any errors

### ISSUE THREAD

**Issue by curt7000** [dummylabs/thewatchman#79]
I am running HA Core 2023.2.1, VENV on Python 3.10.  Integration has been running well for quite some time, thank you!  However, I have some KeyMaster yaml and services that I would like to exclude.  I tried “Configuring” the integration again with the file/folder exceptions but after saving, Watchman no longer identifies known errors that were previously listed and not part of the exception list.  This occurs even after restarting and reloading the integration.

note: I have not removed and attempted to reinstall the integration.

**Comment by filmgarage** [comment]
This is a duplicate of issue #78

**Comment by curt7000** [comment]
Apologies, for some reason the issue never posted on my phone but apparently it did!  Closing this as it is a duplicate.
