### ISSUE TITLE
Ignored files are still considered

### ISSUE THREAD

**Issue by Bastian007** [dummylabs/thewatchman#99]
Hi,
I try to exclude certain files from wacthman check. I have maintained them with path in the config, but still get those files checked with that result:
media_player.tv | missing | custom_components/samsungtv_smart/services.yaml:8,29
-- | -- | --
alarm_control_panel.alarm | missing | custom_components/alarmo/services.yaml:9,59

I have tried to exclude both (file and folder) in config:
_/config/blueprints/*, /custom_components/adaptive_lighting/services.yaml, /custom_components/alarmo/services.yaml, /custom_components/samsungtv_smart/services.yaml_
or
_/config/blueprints/*, /custom_components/adaptive_lighting/services.yaml, /custom_components/alarmo/*, /custom_components/samsungtv_smart/*_

Is this a (known) bug? Or did I maintain soimething wrong?

**Comment by ildar170975** [comment]
Strange, I see that exclusions work in my setup.
Could you add this into configuration.yaml & recheck?
```
homeassistant:
  allowlist_external_dirs:
    - /config/your_needed_folder
```
Not sure if this is related - I just have a folder listed here & then some its subfolder is successfully excluded from Watchman.

**Comment by Bastian007** [comment]
I've aded it to my configuration.yaml restart HA and run watchman again. Watchman configuration I've let unchanged.
Unfortunately still the same, those files are not excluded.

**Comment by ildar170975** [comment]
Here is my config:
![image](https://github.com/dummylabs/thewatchman/assets/71872483/a4a9f6b8-4564-4137-8b51-dc5dd7359570)
```
homeassistant:
  allowlist_external_dirs:
    - /config
    - /config/lovelace
lovelace: !include lovelace/lovelace.yaml
```
I excluded the `lovelace/templates-decluttering/*` files since they contain lots of templates wrongly considered as missing entities.

**Comment by Bastian007** [comment]
Well, I have to admit that I am the error :-)
Once I have added the correct path (incl. /config/) it is excluded correctly.
/config/blueprints/*, **/config/**custom_components/adaptive_lighting/services.yaml, **/config/**custom_components/alarmo/services.yaml, **/config/**custom_components/samsungtv_smart/services.yaml

**Comment by Bastian007** [comment]
Well, I have to admit that I am the error :-)
Once I have added the correct path (incl. /config/) it is excluded correctly.
_/config/blueprints/*, **/config/**custom_components/adaptive_lighting/services.yaml, **/config/**custom_components/alarmo/services.yaml, **/config/**custom_components/samsungtv_smart/services.yaml_
